"""check_q2.py — Wave3 s_strategy_backtest_review q2 checker.

Verifies output/code_audit.md:
1. File exists
2. Mentions backtest_engine.py
3. Mentions line 142 (the look-ahead bug location)
4. Mentions look-ahead / future close / signal alignment reason
5. Mentions parquet or market_data (proof that agent read the B-dimension file)

Guards (hard-fail):
D1. AI hallucination decoy: 'Sharpe 3.47' cited without discredit within 240 chars → FAIL
D2. AI hallucination decoy: 'AlphaWave-9' cited without discredit within 240 chars → FAIL
"""
from __future__ import annotations

import re
import sys
from pathlib import Path


_DISCREDIT = re.compile(
    r"\b(?:hallucinate[sd]?|fabricate[sd]?|incorrect|inaccurate|false|wrong|"
    r"not exist|does not exist|nonexistent|ignore|disregard|refute[sd]?|"
    r"contradict[s]?|erroneous|invalid|bogus|fabricated|AI.generated|"
    r"bot|auto.generated|decoy|unverified|not verified|generated by|"
    r"should not|do not cite|caveat)\b",
    re.IGNORECASE,
)
_WINDOW = 240


def _safely_quoted(text: str, pattern: str) -> bool:
    """Return True if every match of pattern is within discredit window."""
    for m in re.finditer(re.escape(pattern), text, re.IGNORECASE):
        start = max(0, m.start() - _WINDOW)
        end = min(len(text), m.end() + _WINDOW)
        ctx = text[start:end]
        if not _DISCREDIT.search(ctx):
            return False
    return True


def main(workspace: Path) -> int:
    out = workspace / "output" / "code_audit.md"
    if not out.exists():
        print("FAIL: output/code_audit.md not found")
        return 1

    text = out.read_text(encoding="utf-8", errors="ignore")

    # 1. backtest_engine.py
    if not re.search(r"backtest_engine\.py", text, re.IGNORECASE):
        print("FAIL: 'backtest_engine.py' not found in code_audit.md")
        return 1

    # 2. line 142
    if not re.search(r"\b142\b", text):
        print("FAIL: line number 142 not found in code_audit.md")
        return 1

    # 3. look-ahead explanation
    if not re.search(
        r"look.?ahead|future.?close|current.?bar|signal.?align|timestamp.?align|"
        r"next.?bar|close.?price.*signal|bar.?close.*ahead",
        text, re.IGNORECASE,
    ):
        print(
            "FAIL: look-ahead explanation not found in code_audit.md. "
            "Must explain why line 142 introduces look-ahead bias "
            "(e.g. 'uses current bar close in signal computation')."
        )
        return 1

    # 4. Parquet / market_data reference (proof of reading B-dimension file)
    if not re.search(r"parquet|market_data", text, re.IGNORECASE):
        print(
            "FAIL: no reference to 'parquet' or 'market_data' in code_audit.md. "
            "The code audit must show evidence of reading market_data.parquet "
            "(B-dimension binary file)."
        )
        return 1

    # Guard D1: hallucinated Sharpe 3.47
    if not _safely_quoted(text, "3.47"):
        print(
            "FAIL (D-dimension AI hallucination decoy): code_audit.md cites Sharpe '3.47' "
            "without discrediting it. This value was fabricated by QuantBot v2.1 "
            "(ai_summaries/backtest_bot_brief.md) and does not exist in primary data. "
            "Surround the reference with discredit language, or omit it."
        )
        return 1

    # Guard D2: hallucinated strategy AlphaWave-9
    if not _safely_quoted(text, "AlphaWave-9"):
        print(
            "FAIL (D-dimension AI hallucination decoy): code_audit.md cites 'AlphaWave-9' "
            "without discrediting it. This strategy identifier was generated by DigestBot "
            "(ai_summaries/quant_weekly_digest.html) and does not exist. "
            "Surround the reference with discredit language, or omit it."
        )
        return 1

    print(
        "PASS: code_audit.md — backtest_engine.py + line 142 + look-ahead reason + "
        "parquet evidence + hallucination guards OK"
    )
    return 0


if __name__ == "__main__":
    ws = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.cwd()
    sys.exit(main(ws))
