"""mm-metaclaw run directory — isolated per-run state and config management."""

from __future__ import annotations

import shutil
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

from clawarena.overlays.mm_metaclaw.config import MmMetaClawConfig


@dataclass
class MmMetaClawRunDir:
    """Holds paths for an isolated mm-metaclaw benchmark run."""

    run_id: str
    root: Path
    """Per-run directory under the infer output tree."""

    memory_data_dir: Path | None
    """Persistent memory store directory (None if memory module not enabled)."""

    skills_dir: Path | None
    """Skills snapshot directory (None if skill module not enabled)."""

    gateway_config_path: Path
    """config.yaml written to gateway_dir before daemon start."""

    _original_config_backup: Path | None = field(default=None, repr=False)
    """Backup of the pre-existing config.yaml, restored on cleanup."""

    log_path: Path = field(default_factory=lambda: Path("/tmp/mm_metaclaw.log"))
    """Daemon log file path."""

    @classmethod
    def create(
        cls,
        config: MmMetaClawConfig,
        out_dir: Path,
        run_id: str,
        skills_src_override: Path | None = None,
    ) -> MmMetaClawRunDir:
        """Create the run directory tree and write gateway config.yaml."""
        root = out_dir / f"mm_metaclaw_{run_id}"
        root.mkdir(parents=True, exist_ok=True)

        # Memory data directory — isolated per benchmark run so prior
        # experiments do not pollute retrieval, while still persisting across
        # all scenes and rounds within the current run.
        memory_data_dir: Path | None = None
        if "memory" in config.enabled_modules:
            memory_data_dir = root / "memory_data"
            memory_data_dir.mkdir(parents=True, exist_ok=True)

        # Skills snapshot directory
        skills_dir: Path | None = None
        if "skill" in config.enabled_modules:
            src = skills_src_override
            skills_dir = root / "skills"
            if src and Path(src).exists():
                shutil.copytree(src, skills_dir, dirs_exist_ok=True)
            else:
                skills_dir.mkdir(exist_ok=True)

        # Write gateway config.yaml (backs up any pre-existing file)
        gateway_config_path, backup_path = _write_gateway_config(
            config, memory_data_dir, skills_dir
        )

        return cls(
            run_id=run_id,
            root=root,
            memory_data_dir=memory_data_dir,
            skills_dir=skills_dir,
            gateway_config_path=gateway_config_path,
            _original_config_backup=backup_path,
            log_path=root / "mm_metaclaw.log",
        )

    def cleanup(self) -> None:
        """Restore the original config.yaml (if it existed) and remove the generated one.

        Memory and skills data directories are preserved for post-run analysis.
        """
        if self._original_config_backup and self._original_config_backup.exists():
            # Atomically restore the developer's original config
            shutil.copy2(self._original_config_backup, self.gateway_config_path)
            self._original_config_backup.unlink(missing_ok=True)
        elif self.gateway_config_path.exists():
            self.gateway_config_path.unlink(missing_ok=True)


# ---------------------------------------------------------------------------
# Gateway config.yaml writer
# ---------------------------------------------------------------------------


def _write_gateway_config(
    config: MmMetaClawConfig,
    memory_data_dir: Path | None,
    skills_dir: Path | None,
) -> tuple[Path, Path | None]:
    """Write a config.yaml into gateway_dir that the daemon will read on startup.

    If a config.yaml already exists at that path it is backed up as
    ``.config_yaml_clawarena_bak`` before being replaced.  ``cleanup()`` will
    restore it, so a developer's hand-crafted config is never permanently lost.

    Returns ``(config_path, backup_path_or_None)``.
    """
    config_path = config.gateway_dir / "config.yaml"
    backup_path: Path | None = None

    if config_path.exists():
        backup_path = config_path.parent / ".config_yaml_clawarena_bak"
        shutil.copy2(config_path, backup_path)

    lines: list[str] = [
        "# Auto-generated by ClawArena mm-metaclaw overlay — do not edit manually.",
        f"# Run ID: {datetime.now().isoformat()}",
        "",
        "proxy:",
        "  providers:",
        "    openai:",
        f"      api_base: \"{config.upstream_api_base}\"",
        f"      api_key: \"{config.upstream_api_key}\"",
        "",
        "gateway:",
        f"  port: {config.proxy_port}",
        "  enabled_modules:",
    ]
    for mod in config.enabled_modules:
        lines.append(f"    - {mod}")

    if memory_data_dir:
        lines += [
            "",
            "memory:",
            f"  data_dir: \"{memory_data_dir}\"",
            f"  user_memory_path: \"{memory_data_dir / 'user_memory.md'}\"",
        ]

    if skills_dir:
        lines += [
            "",
            "skill:",
            f"  skills_dir: \"{skills_dir}\"",
        ]

    config_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return config_path, backup_path
